version: "3.9"
volumes:
  app:
services:
  web:
    build: .
    volumes:
      - app:/app:Z
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
    restart: unless-stopped
    env_file:
      - .env
