volumes:
  db:
services:
  web:
    image: sitarane/piggy-bank-2000:1.3
    volumes:
      - db:/app/db:Z
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: production
    restart: unless-stopped
